apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  namespace: gitea 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/.gitea-data/"  # This is a directory on the Minikube host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
