apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
  namespace: vaultwarden
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/.vw-data/"  # This is a directory on the Minikube host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
